### ISSUE TITLE
MySQL Database with UTF-8 Encoding

### ISSUE THREAD

**Issue by fiedl** [fiedl/your_platform#74]
## Problem

With our mysql database, which uses a `utf8` encoding, utf characters like "🍕" cannot be stored.

```yml
# database.yml

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ...
  pool: 5
  username: ...
  password: ...
  host: localhost
```

## Related issues

- https://trello.com/c/L29imOT9/1013-e-mails-utf-8-pizza-🍕

## Resources

- https://www.freshworks.com/company/supporting-utf8-characters-in-a-utf8-mysql-table-blog/
- https://adamhooper.medium.com/in-mysql-never-use-utf8-use-utf8mb4-11761243e434
- https://www.joelonsoftware.com/2003/10/08/the-absolute-minimum-every-software-developer-absolutely-positively-must-know-about-unicode-and-character-sets-no-excuses/
